common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['TRAVIS'] ? 'postgres' : 'sales' %>
  password: <%= ENV['TRAVIS'] ? '' : 'sales' %>
  
development:
  database: sales_development
  <<: *common

test:
  database: sales_test
  <<: *common

production:
  database: sales_production
  <<: *common
